//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Products", Namespace="http://www.inriver.com/pim/6/std/3.0")]
[System.Xml.Serialization.XmlRootAttribute("Products", Namespace="http://www.inriver.com/pim/6/std/3.0", IsNullable=false)]
public partial class Products1 {
    
    private Product[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public Product[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class Product {
    
    private object[] productFieldsField;
    
    private ProductLinksType productLinksField;
    
    private object[] productAdditionalsField;
    
    private string entityIdField;
    
    private EntityActions actionField;
    
    private bool actionFieldSpecified;
    
    private string externalUniqueIdFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductChannelNodeId", typeof(ProductFieldsTypeProductChannelNodeId), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductDisplayName", typeof(ProductFieldsTypeProductDisplayName), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductFullDescription", typeof(ProductFieldsTypeProductFullDescription), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductId", typeof(ProductFieldsTypeProductId), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductManufacturer", typeof(ProductFieldsTypeProductManufacturer), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductName", typeof(ProductFieldsTypeProductName), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductSEODescription", typeof(ProductFieldsTypeProductSEODescription), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductSEOKeywords", typeof(ProductFieldsTypeProductSEOKeywords), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductSEOTitle", typeof(ProductFieldsTypeProductSEOTitle), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductSEOURL", typeof(ProductFieldsTypeProductSEOURL), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductShortDescription", typeof(ProductFieldsTypeProductShortDescription), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductTempMappingId", typeof(ProductFieldsTypeProductTempMappingId), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductTranslationReviewed", typeof(ProductFieldsTypeProductTranslationReviewed), IsNullable=false)]
    public object[] ProductFields {
        get {
            return this.productFieldsField;
        }
        set {
            this.productFieldsField = value;
        }
    }
    
    /// <remarks/>
    public ProductLinksType ProductLinks {
        get {
            return this.productLinksField;
        }
        set {
            this.productLinksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SpecificationData", typeof(SpecificationDataType1), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SpecificationTemplate", typeof(SpecificationTemplateType), IsNullable=false)]
    public object[] ProductAdditionals {
        get {
            return this.productAdditionalsField;
        }
        set {
            this.productAdditionalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string EntityId {
        get {
            return this.entityIdField;
        }
        set {
            this.entityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public EntityActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ExternalUniqueIdField {
        get {
            return this.externalUniqueIdFieldField;
        }
        set {
            this.externalUniqueIdFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductChannelNodeId {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SpecificationDataType", Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class SpecificationDataType1 {
    
    private SpecificationDataRowType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Row")]
    public SpecificationDataRowType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class SpecificationDataRowType {
    
    private string[] specificationFieldTypeIdField;
    
    private object[] dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpecificationFieldTypeId")]
    public string[] SpecificationFieldTypeId {
        get {
            return this.specificationFieldTypeIdField;
        }
        set {
            this.specificationFieldTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public object[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class SpecificationTemplateType {
    
    private SpecificationFieldTypeType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpecificationFieldType")]
    public SpecificationFieldTypeType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class SpecificationFieldTypeType {
    
    private string[] idField;
    
    private LocaleStringType[] nameField;
    
    private string[] dataTypeField;
    
    private bool[] mandatoryField;
    
    private string[] indexField;
    
    private string[] categoryIdField;
    
    private LocaleStringType[] categoryNameField;
    
    private string[] defaultValueField;
    
    private string[] cVLIdField;
    
    private bool[] multivalueField;
    
    private string[] unitField;
    
    private string[] additionalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Id")]
    public string[] Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name")]
    public LocaleStringType[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataType")]
    public string[] DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mandatory")]
    public bool[] Mandatory {
        get {
            return this.mandatoryField;
        }
        set {
            this.mandatoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Index", DataType="integer")]
    public string[] Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryId")]
    public string[] CategoryId {
        get {
            return this.categoryIdField;
        }
        set {
            this.categoryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryName")]
    public LocaleStringType[] CategoryName {
        get {
            return this.categoryNameField;
        }
        set {
            this.categoryNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DefaultValue")]
    public string[] DefaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CVLId")]
    public string[] CVLId {
        get {
            return this.cVLIdField;
        }
        set {
            this.cVLIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Multivalue")]
    public bool[] Multivalue {
        get {
            return this.multivalueField;
        }
        set {
            this.multivalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Unit")]
    public string[] Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Additional")]
    public string[] Additional {
        get {
            return this.additionalField;
        }
        set {
            this.additionalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class LocaleStringType {
    
    private LocaleStringTypeLocaleString[] localeStringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocaleString")]
    public LocaleStringTypeLocaleString[] LocaleString {
        get {
            return this.localeStringField;
        }
        set {
            this.localeStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class LocaleStringTypeLocaleString {
    
    private Language languageField;
    
    private string valueField;
    
    /// <remarks/>
    public Language Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum Language {
    
    /// <remarks/>
    da,
    
    /// <remarks/>
    en,
    
    /// <remarks/>
    fi,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    sv,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class SpecificationDataType {
    
    private SpecificationDataRowType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Row")]
    public SpecificationDataRowType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductLinksType {
    
    private object[] productParentLinksField;
    
    private object[] productChildLinksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BundleProduct", typeof(ProductParentLinksTypeBundleProduct), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ChannelNodeProducts", typeof(ProductParentLinksTypeChannelNodeProducts), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FamilyProduct", typeof(ProductParentLinksTypeFamilyProduct), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductRelatedProduct", typeof(ProductParentLinksTypeProductRelatedProduct), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SectionProducts", typeof(ProductParentLinksTypeSectionProducts), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TaskProducts", typeof(ProductParentLinksTypeTaskProducts), IsNullable=false)]
    public object[] ProductParentLinks {
        get {
            return this.productParentLinksField;
        }
        set {
            this.productParentLinksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductBulletPhrase", typeof(ProductChildLinksTypeProductBulletPhrase), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductItem", typeof(ProductChildLinksTypeProductItem), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductRelatedProduct", typeof(ProductChildLinksTypeProductRelatedProduct), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductResource", typeof(ProductChildLinksTypeProductResource), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductSpecifications", typeof(ProductChildLinksTypeProductSpecifications), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductWebRef", typeof(ProductChildLinksTypeProductWebRef), IsNullable=false)]
    public object[] ProductChildLinks {
        get {
            return this.productChildLinksField;
        }
        set {
            this.productChildLinksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeBundleProduct {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private BundleUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeBundleProduct() {
        this.sourceEntityTypeIdField = "Bundle";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BundleUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum BundleUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum LinkActions {
    
    /// <remarks/>
    Deleted,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeChannelNodeProducts {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private ChannelNodeUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeChannelNodeProducts() {
        this.sourceEntityTypeIdField = "ChannelNode";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ChannelNodeUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum ChannelNodeUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeFamilyProduct {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private FamilyUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeFamilyProduct() {
        this.sourceEntityTypeIdField = "Family";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FamilyUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum FamilyUniqueFields {
    
    /// <remarks/>
    EntityId,
    
    /// <remarks/>
    FamilyName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeProductRelatedProduct {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private ProductUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeProductRelatedProduct() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProductUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum ProductUniqueFields {
    
    /// <remarks/>
    EntityId,
    
    /// <remarks/>
    ProductId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeSectionProducts {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private SectionUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeSectionProducts() {
        this.sourceEntityTypeIdField = "Section";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SectionUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum SectionUniqueFields {
    
    /// <remarks/>
    EntityId,
    
    /// <remarks/>
    SectionId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductParentLinksTypeTaskProducts {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private TaskUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string sourceEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductParentLinksTypeTaskProducts() {
        this.sourceEntityTypeIdField = "Task";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TaskUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SourceEntityId {
        get {
            return this.sourceEntityIdField;
        }
        set {
            this.sourceEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum TaskUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductBulletPhrase {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private PhraseUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductBulletPhrase() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Phrase";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PhraseUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum PhraseUniqueFields {
    
    /// <remarks/>
    EntityId,
    
    /// <remarks/>
    PhraseName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductItem {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private ItemUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductItem() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Item";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ItemUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum ItemUniqueFields {
    
    /// <remarks/>
    EntityId,
    
    /// <remarks/>
    ItemId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductRelatedProduct {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private ProductUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductRelatedProduct() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Product";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProductUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductResource {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private ResourceUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductResource() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Resource";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ResourceUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum ResourceUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductSpecifications {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private SpecificationUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductSpecifications() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "Specification";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SpecificationUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum SpecificationUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductChildLinksTypeProductWebRef {
    
    private string sourceEntityTypeIdField;
    
    private string targetEntityTypeIdField;
    
    private WebRefUniqueFields uniqueFieldNameField;
    
    private string uniqueValueField;
    
    private string targetEntityIdField;
    
    private string linkEntityIdField;
    
    private string linkEntityTypeIdField;
    
    private LinkActions actionField;
    
    private bool actionFieldSpecified;
    
    private string sortOrderField;
    
    public ProductChildLinksTypeProductWebRef() {
        this.sourceEntityTypeIdField = "Product";
        this.targetEntityTypeIdField = "WebRef";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceEntityTypeId {
        get {
            return this.sourceEntityTypeIdField;
        }
        set {
            this.sourceEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TargetEntityTypeId {
        get {
            return this.targetEntityTypeIdField;
        }
        set {
            this.targetEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public WebRefUniqueFields UniqueFieldName {
        get {
            return this.uniqueFieldNameField;
        }
        set {
            this.uniqueFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UniqueValue {
        get {
            return this.uniqueValueField;
        }
        set {
            this.uniqueValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string TargetEntityId {
        get {
            return this.targetEntityIdField;
        }
        set {
            this.targetEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityId {
        get {
            return this.linkEntityIdField;
        }
        set {
            this.linkEntityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkEntityTypeId {
        get {
            return this.linkEntityTypeIdField;
        }
        set {
            this.linkEntityTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActionSpecified {
        get {
            return this.actionFieldSpecified;
        }
        set {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum WebRefUniqueFields {
    
    /// <remarks/>
    EntityId,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductDisplayName {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductFullDescription {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductId {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductManufacturer {
    
    private ManufacturerCvl itemField;
    
    private CvlIds cvlField;
    
    private bool cvlFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public ManufacturerCvl Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CvlIds Cvl {
        get {
            return this.cvlField;
        }
        set {
            this.cvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CvlSpecified {
        get {
            return this.cvlFieldSpecified;
        }
        set {
            this.cvlFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum ManufacturerCvl {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    Bisley,
    
    /// <remarks/>
    Gerdsman,
    
    /// <remarks/>
    TestKey,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum CvlIds {
    
    /// <remarks/>
    Manufacturer,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductName {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductSEODescription {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductSEOKeywords {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductSEOTitle {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductSEOURL {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductShortDescription {
    
    private LocaleStringType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public LocaleStringType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductTempMappingId {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.inriver.com/pim/6/std/3.0")]
public partial class ProductFieldsTypeProductTranslationReviewed {
    
    private string itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Data")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.inriver.com/pim/6/std/3.0")]
public enum EntityActions {
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Updated,
    
    /// <remarks/>
    Deleted,
}
